require("prototypes.entity")
require("prototypes.recipe")
require("prototypes.recipe.emc-condensing")
require("prototypes.recipe.emc-developing")
require("prototypes.groups")
require("prototypes.item")
require("prototypes.fluid")
require("prototypes.technology")
